[workspace]
members = [
    "crates/sdf-core",
    "crates/sdf-mesh",
    "crates/sdf-cli",
    "crates/sdf-dsl",
    "crates/sdf-server",
    "crates/sdf-ai",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"
