[package]
name = "sdf-ai"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
sdf-dsl = { path = "../sdf-dsl" }
sdf-mesh = { path = "../sdf-mesh" }
serde_json = "1.0"
ureq = "2.9.1"
